### ISSUE TITLE
Inquiry: Can Akron events be added to this list?

### ISSUE THREAD

**Issue by sorianog** [mrfright/cleveland-tech#23]
Question was raised in cleveland-tech slack: 
> The company I’m starting at is in Akron, but they have several positions open. Is there a general range on that “local” aspect of this Cleveland list or would an Akron company be fair game?  

Also:
> You could ask the maintainer, I think he’s actually in this slack, but I can’t remember his name

**Comment by mrfright** [comment]
You sure can add Akron tech resources to that list!

"Cleveland tech" may not convey the meaning right. It's a resource for people in Cleveland looking for tech resources, and Clevelanders can certainly commute to Akron for a job or meetup. (This whole thing started as a text file on my PC when I was looking for a job, so that's why it has the Clevelander perspective.)

As for me the maintainer on that slack, I was but no longer am. It's a great group, I only left (that group and other groups/social media account, etc.) to not have as many distractions right now.

I'll leave this issue open to maybe put some guidelines for contrubuting.

**Comment by sorianog** [comment]
@mrfright Got it. Thanks for being so quick to respond. Lmk if you need additional/specific help with maintaining this!
