### ISSUE TITLE
Inquiry: Prune Defunct Companies?

### ISSUE THREAD

**Issue by casthewiz** [mrfright/cleveland-tech#24]
I was reviewing the list and noticed Securable.io and Koalah were both present, but I believe both of those companies are currently defunct. Any policy on removing companies that are no longer active?

**Comment by mrfright** [comment]
Thanks for looking at that!

I should make a policy section since others have had other questions, but basically... submit a pull request!

Regarding your particular question, as this a resource for finding companies for jobs for instance, it'd be best to remove defunct companies/resources so we're not wasting anyone's time.

When this was just a private personal list, I kept those links around for posterity or something, but that's all captured in source control so best to get rid of, just like how one shouldn't keep commented-out code.

**Comment by casthewiz** [comment]
Alright, thanks for letting me know! I made a quick pull request removing those two companies.
